<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Prueba Parcial - Sociología de la Desigualdad</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="exam_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="exam_answers_files/libs/quarto-html/quarto.js"></script>
<script src="exam_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="exam_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exam_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="exam_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exam_answers_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exam_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exam_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exam_answers_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="exam_answers_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="exam_answers_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#parte-i-conceptos-y-medición" id="toc-parte-i-conceptos-y-medición" class="nav-link active" data-scroll-target="#parte-i-conceptos-y-medición"><span class="header-section-number">1</span> Parte I: Conceptos y Medición</a>
  <ul class="collapse">
  <li><a href="#medición-de-la-pobreza" id="toc-medición-de-la-pobreza" class="nav-link" data-scroll-target="#medición-de-la-pobreza"><span class="header-section-number">1.1</span> Medición de la pobreza</a>
  <ul class="collapse">
  <li><a href="#calcula-el-ingreso-equivalente-de-cada-hogar-utilizando-θ-1-y-θ-0.5.-completa-la-tabla-con-estos-resultados." id="toc-calcula-el-ingreso-equivalente-de-cada-hogar-utilizando-θ-1-y-θ-0.5.-completa-la-tabla-con-estos-resultados." class="nav-link" data-scroll-target="#calcula-el-ingreso-equivalente-de-cada-hogar-utilizando-θ-1-y-θ-0.5.-completa-la-tabla-con-estos-resultados."><span class="header-section-number">1.1.1</span> Calcula el ingreso equivalente de cada hogar utilizando θ = 1 y θ = 0.5. Completa la tabla con estos resultados.</a></li>
  <li><a href="#calcula-la-tasa-de-pobreza-proporción-de-hogares-pobres-para-ambos-valores-de-θ." id="toc-calcula-la-tasa-de-pobreza-proporción-de-hogares-pobres-para-ambos-valores-de-θ." class="nav-link" data-scroll-target="#calcula-la-tasa-de-pobreza-proporción-de-hogares-pobres-para-ambos-valores-de-θ."><span class="header-section-number">1.1.2</span> Calcula la tasa de pobreza (proporción de hogares pobres) para ambos valores de θ.</a></li>
  <li><a href="#explica-conceptualmente-qué-representa-el-parámetro-θ-y-por-qué-las-tasas-de-pobreza-difieren-entre-ambos-escenarios." id="toc-explica-conceptualmente-qué-representa-el-parámetro-θ-y-por-qué-las-tasas-de-pobreza-difieren-entre-ambos-escenarios." class="nav-link" data-scroll-target="#explica-conceptualmente-qué-representa-el-parámetro-θ-y-por-qué-las-tasas-de-pobreza-difieren-entre-ambos-escenarios."><span class="header-section-number">1.1.3</span> Explica conceptualmente qué representa el parámetro θ y por qué las tasas de pobreza difieren entre ambos escenarios.</a></li>
  </ul></li>
  <li><a href="#curvas-de-lorenz" id="toc-curvas-de-lorenz" class="nav-link" data-scroll-target="#curvas-de-lorenz"><span class="header-section-number">1.2</span> Curvas de Lorenz</a>
  <ul class="collapse">
  <li><a href="#explica-qué-es-una-curva-de-lorenz-y-cómo-se-interpreta-en-términos-de-la-desigualdad-de-ingresos.-qué-representaría-una-línea-diagonal-de-45-grados" id="toc-explica-qué-es-una-curva-de-lorenz-y-cómo-se-interpreta-en-términos-de-la-desigualdad-de-ingresos.-qué-representaría-una-línea-diagonal-de-45-grados" class="nav-link" data-scroll-target="#explica-qué-es-una-curva-de-lorenz-y-cómo-se-interpreta-en-términos-de-la-desigualdad-de-ingresos.-qué-representaría-una-línea-diagonal-de-45-grados"><span class="header-section-number">1.2.1</span> Explica qué es una curva de Lorenz y cómo se interpreta en términos de la desigualdad de ingresos. ¿Qué representaría una línea diagonal de 45 grados?</a></li>
  <li><a href="#compara-las-curvas-de-lorenz-de-nordika-y-txile-en-términos-de-su-nivel-general-de-desigualdad.-cuál-sociedad-presenta-mayor-desigualdad-total-y-por-qué" id="toc-compara-las-curvas-de-lorenz-de-nordika-y-txile-en-términos-de-su-nivel-general-de-desigualdad.-cuál-sociedad-presenta-mayor-desigualdad-total-y-por-qué" class="nav-link" data-scroll-target="#compara-las-curvas-de-lorenz-de-nordika-y-txile-en-términos-de-su-nivel-general-de-desigualdad.-cuál-sociedad-presenta-mayor-desigualdad-total-y-por-qué"><span class="header-section-number">1.2.2</span> Compara las curvas de Lorenz de Nordika y Txile en términos de su nivel general de desigualdad. ¿Cuál sociedad presenta mayor desigualdad total y por qué?</a></li>
  <li><a href="#analiza-los-patrones-de-desigualdad-en-ambas-sociedades.-en-qué-segmentos-de-la-distribución-se-concentran-las-principales-diferencias" id="toc-analiza-los-patrones-de-desigualdad-en-ambas-sociedades.-en-qué-segmentos-de-la-distribución-se-concentran-las-principales-diferencias" class="nav-link" data-scroll-target="#analiza-los-patrones-de-desigualdad-en-ambas-sociedades.-en-qué-segmentos-de-la-distribución-se-concentran-las-principales-diferencias"><span class="header-section-number">1.2.3</span> Analiza los patrones de desigualdad en ambas sociedades. ¿En qué segmentos de la distribución se concentran las principales diferencias?</a></li>
  </ul></li>
  <li><a href="#correlación-de-ingresos-entre-hermanes" id="toc-correlación-de-ingresos-entre-hermanes" class="nav-link" data-scroll-target="#correlación-de-ingresos-entre-hermanes"><span class="header-section-number">1.3</span> Correlación de ingresos entre hermanes</a>
  <ul class="collapse">
  <li><a href="#explica-conceptualmente-qué-mide-esta-correlación-y-por-qué-se-considera-una-medida-de-movilidad-social" id="toc-explica-conceptualmente-qué-mide-esta-correlación-y-por-qué-se-considera-una-medida-de-movilidad-social" class="nav-link" data-scroll-target="#explica-conceptualmente-qué-mide-esta-correlación-y-por-qué-se-considera-una-medida-de-movilidad-social"><span class="header-section-number">1.3.1</span> Explica conceptualmente qué mide esta correlación y por qué se considera una medida de movilidad social:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#parte-ii-aplicación-de-conceptos" id="toc-parte-ii-aplicación-de-conceptos" class="nav-link" data-scroll-target="#parte-ii-aplicación-de-conceptos"><span class="header-section-number">2</span> Parte II: Aplicación de conceptos</a>
  <ul class="collapse">
  <li><a href="#pobreza" id="toc-pobreza" class="nav-link" data-scroll-target="#pobreza"><span class="header-section-number">2.1</span> Pobreza</a>
  <ul class="collapse">
  <li><a href="#usando-una-línea-de-pobreza-de-300-mil-pesos-per-cápita-calcula-la-tasa-de-pobreza-en-cada-generación." id="toc-usando-una-línea-de-pobreza-de-300-mil-pesos-per-cápita-calcula-la-tasa-de-pobreza-en-cada-generación." class="nav-link" data-scroll-target="#usando-una-línea-de-pobreza-de-300-mil-pesos-per-cápita-calcula-la-tasa-de-pobreza-en-cada-generación."><span class="header-section-number">2.1.1</span> Usando una línea de pobreza de 300 mil pesos per cápita, calcula la tasa de pobreza en cada generación.</a></li>
  </ul></li>
  <li><a href="#desigualdad" id="toc-desigualdad" class="nav-link" data-scroll-target="#desigualdad"><span class="header-section-number">2.2</span> Desigualdad</a>
  <ul class="collapse">
  <li><a href="#calcula-el-índice-de-gini-y-el-ratio-entre-el-25-más-rico-y-el-25-más-pobre-para-cada-generación." id="toc-calcula-el-índice-de-gini-y-el-ratio-entre-el-25-más-rico-y-el-25-más-pobre-para-cada-generación." class="nav-link" data-scroll-target="#calcula-el-índice-de-gini-y-el-ratio-entre-el-25-más-rico-y-el-25-más-pobre-para-cada-generación."><span class="header-section-number">2.2.1</span> Calcula el <em>índice de Gini</em> y el <em>ratio entre el 25% más rico y el 25% más pobre</em> para cada generación.</a></li>
  <li><a href="#qué-nos-enseñan-ambas-medidas-sobre-la-desigualdad-en-cada-generación-discute-los-resultados-considerando-ambas-métricas.-por-qué-podrían-ofrecer-diagnósticos-distintos-sobre-la-desigualdad" id="toc-qué-nos-enseñan-ambas-medidas-sobre-la-desigualdad-en-cada-generación-discute-los-resultados-considerando-ambas-métricas.-por-qué-podrían-ofrecer-diagnósticos-distintos-sobre-la-desigualdad" class="nav-link" data-scroll-target="#qué-nos-enseñan-ambas-medidas-sobre-la-desigualdad-en-cada-generación-discute-los-resultados-considerando-ambas-métricas.-por-qué-podrían-ofrecer-diagnósticos-distintos-sobre-la-desigualdad"><span class="header-section-number">2.2.2</span> ¿Qué nos enseñan ambas medidas sobre la desigualdad en cada generación? Discute los resultados considerando ambas métricas. ¿Por qué podrían ofrecer diagnósticos distintos sobre la desigualdad?</a></li>
  </ul></li>
  <li><a href="#movilidad-intergeneracional-del-ingresos" id="toc-movilidad-intergeneracional-del-ingresos" class="nav-link" data-scroll-target="#movilidad-intergeneracional-del-ingresos"><span class="header-section-number">2.3</span> Movilidad intergeneracional del ingresos</a>
  <ul class="collapse">
  <li><a href="#calcula-el-porcentaje-de-movilidad-absoluta-ascendente-y-descendente-en-cada-generación." id="toc-calcula-el-porcentaje-de-movilidad-absoluta-ascendente-y-descendente-en-cada-generación." class="nav-link" data-scroll-target="#calcula-el-porcentaje-de-movilidad-absoluta-ascendente-y-descendente-en-cada-generación."><span class="header-section-number">2.3.1</span> Calcula el porcentaje de movilidad absoluta ascendente y descendente en cada generación.</a></li>
  <li><a href="#calcula-la-elasticidad-intergeneracional-de-ingresos-ige-explica-qué-mide-y-discute-su-magnitud-en-perspectiva-internacional-con-base-en-las-lecturas-de-corak-y-torche." id="toc-calcula-la-elasticidad-intergeneracional-de-ingresos-ige-explica-qué-mide-y-discute-su-magnitud-en-perspectiva-internacional-con-base-en-las-lecturas-de-corak-y-torche." class="nav-link" data-scroll-target="#calcula-la-elasticidad-intergeneracional-de-ingresos-ige-explica-qué-mide-y-discute-su-magnitud-en-perspectiva-internacional-con-base-en-las-lecturas-de-corak-y-torche."><span class="header-section-number">2.3.2</span> Calcula la elasticidad intergeneracional de ingresos (IGE), explica qué mide y discute su magnitud en perspectiva internacional, con base en las lecturas de Corak y Torche.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#parte-iii-discusión" id="toc-parte-iii-discusión" class="nav-link" data-scroll-target="#parte-iii-discusión"><span class="header-section-number">3</span> Parte III: Discusión</a>
  <ul class="collapse">
  <li><a href="#caracteriza-y-compara-ambas-generaciones-en-términos-de-sus-niveles-y-patrones-de-pobreza-desigualdad-y-movilidad." id="toc-caracteriza-y-compara-ambas-generaciones-en-términos-de-sus-niveles-y-patrones-de-pobreza-desigualdad-y-movilidad." class="nav-link" data-scroll-target="#caracteriza-y-compara-ambas-generaciones-en-términos-de-sus-niveles-y-patrones-de-pobreza-desigualdad-y-movilidad."><span class="header-section-number">3.0.1</span> Caracteriza y compara ambas generaciones en términos de sus niveles y patrones de pobreza, desigualdad y movilidad.</a></li>
  <li><a href="#considerando-la-descomposición-de-datt-ravallion-cómo-podría-reducirse-la-pobreza-en-la-generación-2-si-se-descarta-el-crecimiento-económico-como-opción-explica-tu-respuesta." id="toc-considerando-la-descomposición-de-datt-ravallion-cómo-podría-reducirse-la-pobreza-en-la-generación-2-si-se-descarta-el-crecimiento-económico-como-opción-explica-tu-respuesta." class="nav-link" data-scroll-target="#considerando-la-descomposición-de-datt-ravallion-cómo-podría-reducirse-la-pobreza-en-la-generación-2-si-se-descarta-el-crecimiento-económico-como-opción-explica-tu-respuesta."><span class="header-section-number">3.0.2</span> Considerando la descomposición de Datt-Ravallion, ¿cómo podría reducirse la pobreza en la Generación 2 si se descarta el crecimiento económico como opción? Explica tu respuesta.</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="exam_answers.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prueba Parcial - Sociología de la Desigualdad</h1>
<p class="subtitle lead">SOL186S - Primer Semestre 2025</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Información general</strong></p>
<ul>
<li><p>Tienen hasta las 12:00pm para completar la prueba</p></li>
<li><p>Se permite el uso de calculadora y apuntes.</p></li>
<li><p>Es obligatorio mostrar todos los procedimientos de cálculo.</p></li>
<li><p>No está permitido el uso de computadores, tablets ni teléfonos celulares durante el examen</p></li>
<li><p>Puntaje total: 100 puntos.</p></li>
</ul>
</div>
</div>
<section id="parte-i-conceptos-y-medición" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Parte I: Conceptos y Medición</h1>
<section id="medición-de-la-pobreza" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="medición-de-la-pobreza"><span class="header-section-number">1.1</span> Medición de la pobreza</h2>
<p>A continuación se presentan datos de cinco hogares con sus respectivos ingresos y número de miembros:</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Datos de ingresos y composición de hogares</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Hogar</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Ingreso Total (miles pesos)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Número de Miembros</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Ingreso per Cápita</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Ingreso equivalente (θ=0.5)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">800</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">1200</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">1500</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">2000</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">E</td>
<td style="text-align: center;">3000</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Considerando una línea de pobreza es de 300 mil pesos por persona y la siguiente fórmula de ingreso equivalente por tamaño del hogar, realiza los cálculos requeridos a continuación:</p>
<p><span class="math display">\[\text{Ingreso equivalente} = \frac{\text{Ingreso total del hogar}}{(\text{Número de miembros})^θ}\]</span></p>
<section id="calcula-el-ingreso-equivalente-de-cada-hogar-utilizando-θ-1-y-θ-0.5.-completa-la-tabla-con-estos-resultados." class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="calcula-el-ingreso-equivalente-de-cada-hogar-utilizando-θ-1-y-θ-0.5.-completa-la-tabla-con-estos-resultados."><span class="header-section-number">1.1.1</span> Calcula el ingreso equivalente de cada hogar utilizando θ = 1 y θ = 0.5. Completa la tabla con estos resultados.</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 21%">
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Hogar</th>
<th style="text-align: center;">Ingreso Total</th>
<th style="text-align: center;">Miembros</th>
<th style="text-align: center;"><span class="math inline">\(\theta = 1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\theta = 0.5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">800</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(\frac{800}{4^1} = 200\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{800}{\sqrt{4}} = 400\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">1200</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(\frac{1200}{3^1} = 400\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1200}{\sqrt{3}} \approx 692.8\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">1500</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"><span class="math inline">\(\frac{1500}{5^1} = 300\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1500}{\sqrt{5}} \approx 670.8\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">2000</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(\frac{2000}{4^1} = 500\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{2000}{\sqrt{4}} = 1000\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">E</td>
<td style="text-align: center;">3000</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;"><span class="math inline">\(\frac{3000}{6^1} = 500\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{3000}{\sqrt{6}} \approx 1224.7\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="calcula-la-tasa-de-pobreza-proporción-de-hogares-pobres-para-ambos-valores-de-θ." class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="calcula-la-tasa-de-pobreza-proporción-de-hogares-pobres-para-ambos-valores-de-θ."><span class="header-section-number">1.1.2</span> Calcula la tasa de pobreza (proporción de hogares pobres) para ambos valores de θ.</h3>
<p><strong>Respuesta:</strong></p>
<p>La línea de pobreza es de <strong>300 mil pesos por persona equivalente</strong>.</p>
<ul>
<li><p>Con <span class="math inline">\(\theta = 1\)</span>, el único hogar por debajo de la línea es el hogar A (200).<br>
<span class="math display">\[
\text{Tasa de pobreza} = \frac{1}{5} = 0.2 = 20\%
\]</span></p></li>
<li><p>Con <span class="math inline">\(\theta = 0.5\)</span>, todos los hogares tienen ingresos equivalentes superiores a 300.<br>
<span class="math display">\[
\text{Tasa de pobreza} = 0\%
\]</span></p></li>
</ul>
</section>
<section id="explica-conceptualmente-qué-representa-el-parámetro-θ-y-por-qué-las-tasas-de-pobreza-difieren-entre-ambos-escenarios." class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="explica-conceptualmente-qué-representa-el-parámetro-θ-y-por-qué-las-tasas-de-pobreza-difieren-entre-ambos-escenarios."><span class="header-section-number">1.1.3</span> Explica conceptualmente qué representa el parámetro θ y por qué las tasas de pobreza difieren entre ambos escenarios.</h3>
<p><strong>Respuesta:</strong></p>
<p>El parámetro <span class="math inline">\(\theta\)</span> representa cómo se ajusta el ingreso del hogar según el tamaño del hogar, capturando las <strong>economías de escala</strong> en el consumo:</p>
<ul>
<li><p>Cuando <span class="math inline">\(\theta = 1\)</span>, se asume que cada miembro adicional requiere la misma cantidad de recursos, es decir, <strong>no hay economías de escala</strong>.</p></li>
<li><p>Cuando <span class="math inline">\(\theta = 0.5\)</span>, se reconoce que los miembros del hogar pueden <strong>compartir recursos</strong> (vivienda, servicios, alimentos), por lo que el costo por persona disminuye.</p></li>
<li><p>Por esta razón, la tasa de pobreza es menor con <span class="math inline">\(\theta = 0.5\)</span>: los hogares grandes no son penalizados por su tamaño, y su ingreso ajustado refleja mejor su capacidad de consumo conjunta.</p></li>
</ul>
</section>
</section>
<section id="curvas-de-lorenz" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="curvas-de-lorenz"><span class="header-section-number">1.2</span> Curvas de Lorenz</h2>
<p>A continuación se presenta el gráfico de las curvas de Lorenz para dos sociedades hipotéticas, Nordika y Txile.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="exam_answers_files/figure-html/lorenz-curves-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>A partir de este gráfico responde las siguientes preguntas:</p>
<section id="explica-qué-es-una-curva-de-lorenz-y-cómo-se-interpreta-en-términos-de-la-desigualdad-de-ingresos.-qué-representaría-una-línea-diagonal-de-45-grados" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="explica-qué-es-una-curva-de-lorenz-y-cómo-se-interpreta-en-términos-de-la-desigualdad-de-ingresos.-qué-representaría-una-línea-diagonal-de-45-grados"><span class="header-section-number">1.2.1</span> Explica qué es una curva de Lorenz y cómo se interpreta en términos de la desigualdad de ingresos. ¿Qué representaría una línea diagonal de 45 grados?</h3>
<p><strong>Respuesta:</strong></p>
<p>La <strong>curva de Lorenz</strong> es una herramienta gráfica utilizada para representar la <strong>distribución del ingreso o la riqueza</strong> en una sociedad. En el eje horizontal se muestra la <strong>proporción acumulada de la población</strong>, ordenada de menor a mayor ingreso, y en el eje vertical se muestra la <strong>proporción acumulada del ingreso total</strong> que posee ese porcentaje de población.</p>
<ul>
<li><p>Una <strong>línea diagonal de 45 grados</strong> representa la <strong>igualdad perfecta</strong>, donde cada porcentaje de la población recibe el mismo porcentaje de ingreso (por ejemplo, el 20% más pobre recibe el 20% del ingreso total).</p></li>
<li><p>Cuanto <strong>más alejada</strong> esté la curva de Lorenz de esa diagonal, <strong>mayor es la desigualdad</strong>: indica que una proporción pequeña de la población concentra una parte mayor del ingreso.</p></li>
</ul>
</section>
<section id="compara-las-curvas-de-lorenz-de-nordika-y-txile-en-términos-de-su-nivel-general-de-desigualdad.-cuál-sociedad-presenta-mayor-desigualdad-total-y-por-qué" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="compara-las-curvas-de-lorenz-de-nordika-y-txile-en-términos-de-su-nivel-general-de-desigualdad.-cuál-sociedad-presenta-mayor-desigualdad-total-y-por-qué"><span class="header-section-number">1.2.2</span> Compara las curvas de Lorenz de Nordika y Txile en términos de su nivel general de desigualdad. ¿Cuál sociedad presenta mayor desigualdad total y por qué?</h3>
<p><strong>Respuesta:</strong></p>
<p>Al comparar las curvas de Lorenz:</p>
<ul>
<li><p><strong>Txile</strong> presenta <strong>mayor desigualdad</strong> que <strong>Nordika</strong>. Esto se observa porque su curva está <strong>más alejada de la diagonal de igualdad perfecta</strong> y se encuentra <strong>por debajo</strong> de la curva de Nordika en casi todos los tramos.</p></li>
<li><p>Por ejemplo, el <strong>40% más pobre</strong> de la población en Txile acumula solo <strong>8%</strong> del ingreso, mientras que en Nordika el mismo grupo concentra <strong>18%</strong>, lo cual indica una distribución más equitativa en Nordika.</p></li>
</ul>
<p>Si se calculara el <strong>índice de Gini</strong>, se esperaría un valor <strong>mayor en Txile</strong>, lo que confirmaría su <strong>mayor nivel de desigualdad</strong> total.</p>
</section>
<section id="analiza-los-patrones-de-desigualdad-en-ambas-sociedades.-en-qué-segmentos-de-la-distribución-se-concentran-las-principales-diferencias" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="analiza-los-patrones-de-desigualdad-en-ambas-sociedades.-en-qué-segmentos-de-la-distribución-se-concentran-las-principales-diferencias"><span class="header-section-number">1.2.3</span> Analiza los patrones de desigualdad en ambas sociedades. ¿En qué segmentos de la distribución se concentran las principales diferencias?</h3>
<p><strong>Respuesta:</strong></p>
<ul>
<li><p>En los <strong>primeros quintiles</strong> (0–40% de la población), <strong>Nordika</strong> entrega una mayor proporción del ingreso a los hogares más pobres. En <strong>Txile</strong>, en cambio, la curva crece muy lentamente al inicio, lo que significa que los <strong>hogares más pobres capturan una porción mínima del ingreso total</strong>.</p></li>
<li><p>A partir del <strong>80% de la población acumulada</strong>, ambas curvas se acercan, indicando que la diferencia de desigualdad es menor entre los sectores más ricos. Es decir, las principales brechas entre Txile y Nordika están en la <strong>base de la distribución</strong>, donde se concentra la mayor exclusión en Txile.</p></li>
</ul>
</section>
</section>
<section id="correlación-de-ingresos-entre-hermanes" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="correlación-de-ingresos-entre-hermanes"><span class="header-section-number">1.3</span> Correlación de ingresos entre hermanes</h2>
<p>En la imagen a continuación, cada pila de monedas representa los ingresos de les hijes de una misma familia. A partir de esta representación y de la fórmula de la <strong>correlación entre hermanes</strong>:</p>
<section id="explica-conceptualmente-qué-mide-esta-correlación-y-por-qué-se-considera-una-medida-de-movilidad-social" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="explica-conceptualmente-qué-mide-esta-correlación-y-por-qué-se-considera-una-medida-de-movilidad-social"><span class="header-section-number">1.3.1</span> Explica conceptualmente qué mide esta correlación y por qué se considera una medida de movilidad social:</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://www.harveker.com/blog/wp-content/uploads/sites/2/2018/10/Rich-vs-Poor.png" class="img-fluid figure-img"></p>
<figcaption>hermanes</figcaption>
</figure>
</div>
<p>Formalmente, la correlación de ingresos entre hermanes se define como sigue:</p>
<p><span class="math display">\[
\rho = \frac{\sigma^2_{\text{entre}}}{\sigma^2_{\text{entre}} + \sigma^2_{\text{dentro}}}
\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\sigma^2_{\text{entre}}\)</span> es la <strong>varianza entre familias</strong>, es decir, la parte de la desigualdad en ingresos que se debe a diferencias sistemáticas entre familias,</p></li>
<li><p><span class="math inline">\(\sigma^2_{\text{dentro}}\)</span> es la <strong>varianza dentro de las familias</strong>, es decir, la desigualdad en ingresos entre hermanes de una misma familia.</p></li>
</ul>
<p><strong>Respuesta:</strong></p>
<p>La correlación de ingresos entre hermanes mide cuánto se parecen los ingresos de les hermanes entre sí. Es un indicador de cuánto influye el origen familiar sobre los resultados económicos individuales.</p>
<ul>
<li><p>Si <span class="math inline">\(\rho \approx 1\)</span>, entonces toda la desigualdad se explica por diferencias entre familias. En la imagen, esto se vería como pilas de monedas de igual altura dentro de cada familia, pero alturas muy distintas entre familias. En este caso, la movilidad social es baja o nula.</p></li>
<li><p>Si <span class="math inline">\(\rho \approx 0\)</span>, entonces la mayoría de la desigualdad ocurre dentro de las familias: les hermanes pueden terminar con ingresos muy distintos, independientemente del origen familiar. En la imagen, las pilas de monedas dentro de una familia tendrían alturas muy distintas, y se parecerían a las pilas de otras familias. En este caso, la movilidad social es alta.</p></li>
</ul>
<p>La correlación entre hermanes captura cuánto importa la suerte de nacer en una familia específica. Si los ingresos de les hermanes son muy similares (alta correlación), entonces el contexto familiar es determinante. Esto refleja una estructura social rígida, con baja movilidad social. Por el contrario, una baja correlación sugiere que, incluso dentro de una misma familia, existen trayectorias muy diversas, lo cual es consistente con una sociedad de alta movilidad, donde factores individuales, oportunidades externas o decisiones personales influyen más que el origen familiar.</p>
</section>
</section>
</section>
<section id="parte-ii-aplicación-de-conceptos" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Parte II: Aplicación de conceptos</h1>
<p>A continuación se presentan los ingresos anuales (en miles de pesos) de 4 familias a lo largo de dos generaciones: padres/madres (Generación 1) e hijos/as (Generación 2).</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla de ingresos</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Familia</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Ingreso Gen 1 (mil pesos)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Ingreso Gen 2 (mil pesos)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">50</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">200</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">600</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">950</td>
<td style="text-align: center;">1550</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<section id="pobreza" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="pobreza"><span class="header-section-number">2.1</span> Pobreza</h2>
<section id="usando-una-línea-de-pobreza-de-300-mil-pesos-per-cápita-calcula-la-tasa-de-pobreza-en-cada-generación." class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="usando-una-línea-de-pobreza-de-300-mil-pesos-per-cápita-calcula-la-tasa-de-pobreza-en-cada-generación."><span class="header-section-number">2.1.1</span> Usando una línea de pobreza de 300 mil pesos per cápita, calcula la tasa de pobreza en cada generación.</h3>
<p><strong>Respuesta:</strong></p>
<p><span class="math display">\[\text{Tasa de pobreza} = \frac{\text{número de personas con ingreso} &lt; 300}{4}\]</span></p>
<ul>
<li><p><strong>Generación 1</strong>: Las personas A y B tienen ingresos de 100 y 250 mil pesos, respectivamente, ubicándolas bajo la línea de pobreza. Las personas C y D tienen ingresos superiores a 300 mil pesos. Por tanto, la asa de pobreza en Gen 1 es: <span class="math inline">\(\frac{2}{4} = 0.5\)</span> (50%).</p></li>
<li><p><strong>Generación 2</strong>: Las personas A y B tienen ingresos de 50 y 200 mil pesos, respectivamente, manteniéndolas bajo la línea de pobreza. Las personas C y D superan el umbral de 300 mil pesos. Por tanto, la asa de pobreza en Gen 2 es: <span class="math inline">\(\frac{2}{4} = 0.5\)</span> (50%).</p></li>
</ul>
</section>
</section>
<section id="desigualdad" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="desigualdad"><span class="header-section-number">2.2</span> Desigualdad</h2>
<section id="calcula-el-índice-de-gini-y-el-ratio-entre-el-25-más-rico-y-el-25-más-pobre-para-cada-generación." class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="calcula-el-índice-de-gini-y-el-ratio-entre-el-25-más-rico-y-el-25-más-pobre-para-cada-generación."><span class="header-section-number">2.2.1</span> Calcula el <em>índice de Gini</em> y el <em>ratio entre el 25% más rico y el 25% más pobre</em> para cada generación.</h3>
<p>Para aproximar el coeficiente de Gini utiliza la siguiente fórmula:</p>
<p><span class="math display">\[G = \frac{\sum_{i=1}^{n} \sum_{j=1}^{n} |y_i - y_j|}{2n^2 \bar{y}}\]</span></p>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(G\)</span> es el índice de Gini, que mide la desigualdad. Su valor oscila entre 0 y 1.</p></li>
<li><p><span class="math inline">\(\sum_{i=1}^{n} \sum_{j=1}^{n} |y_i - y_j|\)</span> es la suma de las diferencias absolutas entre los ingresos.</p></li>
<li><p><span class="math inline">\(n\)</span> es el número de personas en la sociedad. En este caso, <span class="math inline">\(n = 4\)</span>.</p></li>
<li><p><span class="math inline">\(\bar{y}\)</span> es el ingreso promedio de la sociedad.</p></li>
</ul>
<p><strong>Respuesta:</strong></p>
<p>Cálculo de Gini Gen 1:</p>
<ul>
<li><p><span class="math inline">\(\bar{y} = \frac{100 + 250 + 500 + 950}{4} = 450\)</span> mil pesos</p></li>
<li><p><span class="math inline">\(\sum |y_i - y_j| = |100 - 250| + |100 - 500| + |100 - 950| + |250 - 500| + |250 - 950| + |500 - 950|\)</span></p></li>
<li><p><span class="math inline">\(\sum |y_i - y_j| = 150 + 400 + 850 + 250 + 700 + 450 = 2.700\)</span> mil pesos</p></li>
</ul>
<p>El índice de Gini para la <strong>Generación 1</strong> es:</p>
<p><span class="math display">\[G = \frac{2.700}{2 \times 4^2 \times 450} = \frac{2.700}{2 \times 16 \times 450} = \frac{2.700}{14.400} = 0.4875 \approx 0.49\]</span></p>
<p>Cálculo de Gini Gen 2:</p>
<ul>
<li><p><span class="math inline">\(\bar{y} = \frac{50 + 200 + 600 + 1550}{4} = 600\)</span> mil pesos</p></li>
<li><p><span class="math inline">\(\sum |y_i - y_j| = |50 - 200| + |50 - 600| + |50 - 1550| + |200 - 600| + |200 - 1550| + |600 - 1550|\)</span></p></li>
<li><p><span class="math inline">\(\sum |y_i - y_j| = 150 + 550 + 1500 + 400 + 1350 + 950 = 4.900\)</span> mil pesos</p></li>
</ul>
<p>El índice de Gini para la <strong>Generación 2</strong> es:</p>
<p><span class="math display">\[G = \frac{4.900}{2 \times 4^2 \times 600} = \frac{4.900}{2 \times 16 \times 600} = \frac{4.900}{19.200} = 0.5104 \approx 0.51\]</span></p>
<p>Calculo el ratio entre el 25% más rico y el 25% más pobre en cada generación:</p>
<p><span class="math display">\[\text{Ratio} = \frac{\text{Ingreso más alto}}{\text{Ingreso más bajo}}\]</span></p>
<ul>
<li><p><strong>Generación 1</strong>: Ratio <span class="math inline">\(= \frac{950}{100} = 9.5\)</span></p></li>
<li><p><strong>Generación 2</strong>: Ratio <span class="math inline">\(= \frac{1550}{50} = 31\)</span></p></li>
</ul>
</section>
<section id="qué-nos-enseñan-ambas-medidas-sobre-la-desigualdad-en-cada-generación-discute-los-resultados-considerando-ambas-métricas.-por-qué-podrían-ofrecer-diagnósticos-distintos-sobre-la-desigualdad" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="qué-nos-enseñan-ambas-medidas-sobre-la-desigualdad-en-cada-generación-discute-los-resultados-considerando-ambas-métricas.-por-qué-podrían-ofrecer-diagnósticos-distintos-sobre-la-desigualdad"><span class="header-section-number">2.2.2</span> ¿Qué nos enseñan ambas medidas sobre la desigualdad en cada generación? Discute los resultados considerando ambas métricas. ¿Por qué podrían ofrecer diagnósticos distintos sobre la desigualdad?</h3>
<p><strong>Respuesta:</strong></p>
<p>Ambas medidas buscan capturar el grado de desigualdad en la distribución del ingreso, pero lo hacen desde perspectivas distintas, por lo que pueden ofrecer diagnósticos complementarios o incluso divergentes. En este caso,</p>
<ul>
<li><strong>Gini</strong>:
<ul>
<li>Generación 1: <span class="math inline">\(G = 0.49\)</span></li>
<li>Generación 2: <span class="math inline">\(G = 0.51\)</span></li>
</ul></li>
<li><strong>Ratio entre extremos</strong>:
<ul>
<li>Generación 1: <span class="math inline">\(\frac{950}{100} = 9.5\)</span></li>
<li>Generación 2: <span class="math inline">\(\frac{1550}{50} = 31\)</span></li>
</ul></li>
</ul>
<p>El índice de Gini considera todas las diferencias entre todos los pares de ingresos, por lo que ofrece una medida global de la desigualdad. Es más sensibles a cambios en la parte media de la distribución de ingresos, pero menos sensible a cambios en los extremos. En cambio, el ratio entre extremos sólo compara dos puntospor tanto es sensible a cambios en los extremos de la distribución, pero ignora lo que pasa con el resto de la población.</p>
<p>En este caso se observa que el Gini prácticamente no cambia pero hay aumento dramático del ratio (de 9.5 a 31), indicando que la concentración del ingreso en el extremo superior creció mucho más rápido que la mejora de los ingresos en otros sectores.</p>
</section>
</section>
<section id="movilidad-intergeneracional-del-ingresos" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="movilidad-intergeneracional-del-ingresos"><span class="header-section-number">2.3</span> Movilidad intergeneracional del ingresos</h2>
<section id="calcula-el-porcentaje-de-movilidad-absoluta-ascendente-y-descendente-en-cada-generación." class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="calcula-el-porcentaje-de-movilidad-absoluta-ascendente-y-descendente-en-cada-generación."><span class="header-section-number">2.3.1</span> Calcula el porcentaje de movilidad absoluta ascendente y descendente en cada generación.</h3>
<p><strong>Respuesta:</strong></p>
<ul>
<li><p><strong>Movilidad ascendente</strong>: Las personas C y D aumentaron sus ingresos (de 500 a 600 y de 950 a 1550 mil pesos, respectivamente).</p></li>
<li><p><strong>Movilidad descendente</strong>: Las personas A y B disminuyeron sus ingresos (de 100 a 50 y de 250 a 200 mil pesos, respectivamente).</p></li>
<li><p><strong>% movilidad ascendente</strong>: <span class="math inline">\(\frac{2}{4} = 0.5\)</span> (50%).</p></li>
<li><p><strong>% movilidad descendente</strong>: <span class="math inline">\(\frac{2}{4} = 0.5\)</span> (50%).</p></li>
</ul>
</section>
<section id="calcula-la-elasticidad-intergeneracional-de-ingresos-ige-explica-qué-mide-y-discute-su-magnitud-en-perspectiva-internacional-con-base-en-las-lecturas-de-corak-y-torche." class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="calcula-la-elasticidad-intergeneracional-de-ingresos-ige-explica-qué-mide-y-discute-su-magnitud-en-perspectiva-internacional-con-base-en-las-lecturas-de-corak-y-torche."><span class="header-section-number">2.3.2</span> Calcula la elasticidad intergeneracional de ingresos (IGE), explica qué mide y discute su magnitud en perspectiva internacional, con base en las lecturas de Corak y Torche.</h3>
<p>Para ello, usa la siguiente fórmula:</p>
<p><span class="math display">\[\text{Elasticidad} = \frac{\text{Cov}(x, y)}{\text{Var}(x)}\]</span></p>
<p>donde las siguientes cantidades resumen la información contenida en los datos de ingreso tranformados a logaritmo en base 10.</p>
<ul>
<li><span class="math inline">\(\bar{x} = 2.52\)</span>, <span class="math inline">\(\bar{y} = 2.49\)</span></li>
<li><span class="math inline">\(\text{Var}(x) = 0.174\)</span>, <span class="math inline">\(\text{Cov}(x, y) = 0.087\)</span></li>
</ul>
<p>datos:</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">Persona</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">log Gen 1 (x)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 62, 80, 255) !important;">log Gen 2 (y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">2.00</td>
<td style="text-align: center;">1.70</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">2.40</td>
<td style="text-align: center;">2.30</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">2.70</td>
<td style="text-align: center;">2.78</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">2.98</td>
<td style="text-align: center;">3.19</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p><strong>Respuesta:</strong></p>
<p><span class="math display">\[
\text{Elasticidad} = \frac{0.087}{0.174} = 0.5
\]</span></p>
<p>Una elasticidad de <strong>0.5</strong> indica que el 50% de las diferencias relativas en ingresos entre padres y madres se transmiten a sus hijos e hijas. En otras palabras, las personas cuyos padres tienen ingresos altos tienden a tener ingresos altos también, y viceversa.</p>
<p>Según Corak, las sociedades con alta elasticidad (por sobre 0.4) se caracterizan por una baja movilidad intergeneracional y una fuerte reproducción de las desigualdades económicas. Este valor ubicaría a esta sociedad hipotética en un nivel de movilidad similar al de países con alta desigualdad y baja movilidad como Estados Unidos. En contraste, países como Dinamarca, Canadá o Noruega muestran elasticidades entre 0.15 y 0.2, lo que refleja mayores oportunidades de movilidad económica.</p>
<p>Como señala Torche, una elasticidad de 0.5 no solo refleja que los ingresos se heredan parcialmente, sino también que las instituciones sociales y económicas amplifican las ventajas iniciales. Este resultado es consistente con una estructura social en la que las oportunidades están fuertemente condicionadas por el origen familiar.</p>
</section>
</section>
</section>
<section id="parte-iii-discusión" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Parte III: Discusión</h1>
<p>Considerando todos los resultados obtenidos en la Parte II,</p>
<section id="caracteriza-y-compara-ambas-generaciones-en-términos-de-sus-niveles-y-patrones-de-pobreza-desigualdad-y-movilidad." class="level3" data-number="3.0.1">
<h3 data-number="3.0.1" class="anchored" data-anchor-id="caracteriza-y-compara-ambas-generaciones-en-términos-de-sus-niveles-y-patrones-de-pobreza-desigualdad-y-movilidad."><span class="header-section-number">3.0.1</span> Caracteriza y compara ambas generaciones en términos de sus niveles y patrones de pobreza, desigualdad y movilidad.</h3>
<p>Para responder a esta pregunta no olvides referirte los siguientes conceptos (si corresponde):</p>
<ul>
<li>pobreza absoluta y pobreza relativa</li>
<li>distribución del ingreso</li>
<li>movilidad absoluta y movilidad relativa</li>
</ul>
<p><strong>Respuesta:</strong></p>
<ul>
<li><p>No hay reducción de la pobreza absoluta entre generaciones.</p></li>
<li><p>Hay un leve aumento en el ingreso promedio y estabilidad de la desigualdad global (según Gini).</p></li>
<li><p>Se observa un fuerte crecimiento en la distancia entre ricos y pobres (según ratio).</p></li>
<li><p>Hay movilidad absoluta en ambas direcciones pero la movilidad relativa es baja.</p></li>
</ul>
<p>En conjunto, esto indica una sociedad con crecimiento económico desigual y persistencia estructural de las desventaja.</p>
</section>
<section id="considerando-la-descomposición-de-datt-ravallion-cómo-podría-reducirse-la-pobreza-en-la-generación-2-si-se-descarta-el-crecimiento-económico-como-opción-explica-tu-respuesta." class="level3" data-number="3.0.2">
<h3 data-number="3.0.2" class="anchored" data-anchor-id="considerando-la-descomposición-de-datt-ravallion-cómo-podría-reducirse-la-pobreza-en-la-generación-2-si-se-descarta-el-crecimiento-económico-como-opción-explica-tu-respuesta."><span class="header-section-number">3.0.2</span> Considerando la descomposición de Datt-Ravallion, ¿cómo podría reducirse la pobreza en la Generación 2 si se descarta el crecimiento económico como opción? Explica tu respuesta.</h3>
<p><strong>Respuesta:</strong></p>
<p>Si el crecimiento económico no es una opción, la reducción de la pobreza debe apoyarse en políticas de redistribución. En esta sociedad hipotética, reducir la concentración de ingresos en el extremo superior (como se refleja en el ratio 31) podría liberar recursos para mejorar los ingresos de quienes están bajo la línea de pobreza. Por ejemplo, políticas fiscales redistributivas o transferencias directas podrían mejorar los ingresos reales de los hogares pobres, incluso sin aumentar el ingreso nacional total.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fin del examen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Revisa tus respuestas antes de entregar.</p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>